version: '3'

volumes:
  production_traefik: {}

services:
    db:
        image: postgres
        volumes:
            - /var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: ./compose/local/rails/Dockerfile
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        volumes:
            - .:/myapp
        depends_on:
            - db
    traefik:
        build:
            context: .
            dockerfile: ./compose/production/traefik/Dockerfile
        image: production_traefik
        depends_on:
            - web
        volumes:
            - production_traefik:/etc/traefik/acme
        ports:
            - "0.0.0.0:80:80"
            - "0.0.0.0:443:443"
